---
- hosts: pgpool
  gather_facts: yes
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    role_path: "{{ lookup('env', 'ROLE_PATH') }}"
  pre_tasks:
    - name: Install dependencies
      apt: 
        name: 
          - python3-apt
          - vim
        update_cache: yes
    - name: Use python3 by default
      alternatives: 
        path: /usr/bin/python3
        link: /usr/bin/python
        name: python
        priority: 1
  roles:
    - name: "{{ role_path if role_path is defined and role_path else lookup('env', 'HOME') + '/ansible-role-pgpool' }}"
