---
- hosts: pgpool
  gather_facts: yes
  become: yes
  pre_tasks:
    - name: Install dependencies
      apt: 
        name: 
          - python3-apt
          - vim
        update_cache: yes
    - name: Use python3 by default
      alternatives: 
        path: /usr/bin/python3
        link: /usr/bin/python
        name: python
        priority: 1
    - name: PostgreSQL and Pgpool2 | set owner and umask for certifcates to postgres
      ansible.builtin.shell:
        cmd: |
          chown postgres /etc/pgpool2/server.key /etc/pgpool2/server.cert
          chmod 0600 /etc/pgpool2/server.key /etc/pgpool2/server.cert
        executable: /bin/bash
      become: yes
      become_user: "root"
      ignore_errors: yes
  roles:
    - name: pgpool
      vars:
        pgpool_scram_sha_256_key: pgpool_scram_sha_256_key_replace
        postgresql_manager_user: admin
        postgresql_manager_password: postgresql_manager_password_replace
        postgresql_monitoring_user: monitoring
        postgresql_monitoring_password: postgresql_monitoring_password_replace
