---
# https://wiki.postgresql.org/wiki/Apt 
- name: Apt | Make sure the CA certificates are available
  ansible.builtin.apt:
    name: 
      - ca-certificates
      - gnupg
    state: present

- name: Apt | Add PostgreSQL repository apt-key
  ansible.builtin.apt_key:
    id: "{{ pgpool_apt_key_id }}"
    url: "{{ pgpool_apt_key_url }}"
    state: present

- name: Apt | Add PostgreSQL repository
  ansible.builtin.apt_repository:
    repo: "{{ pgpool_apt_repository }}"
    state: present

- name: Apt | Add PostgreSQL archive repository
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
    filename: apt-archive.postgresql.org
  loop: "{{ pgpool_apt_archive_repositories }}"

- name: Apt | Add PostgreSQL repository preferences
  ansible.builtin.template:
    src: apt_postgresql_org_pub_repos_apt.j2
    dest: /etc/apt/preferences.d/apt_postgresql_org_pub_repos_apt.pref
    mode: 0644

- name: Apt | Define PgPool version to be installed
  ansible.builtin.set_fact:
    pgpool2_apt: pgpool2={{ pgpool_version_debian }}
  when: pgpool_version_debian is defined and pgpool_version_debian != ''

- name: Apt | Install PgPool
  ansible.builtin.apt:
    name: "{{ pgpool2_apt | default('pgpool2') }}"
    state: present
    update_cache: yes
    default_release: "{{ ansible_distribution_release + '-pgdg' }}"
    cache_valid_time: 3600
  register: pgpool_install

- name: Apt | Install dependencies
  ansible.builtin.apt:
    name: "{{ pgpool_apt_dependencies }}"
    state: present

- name: Apt | Install extensions
  community.postgresql.postgresql_query:
    db: "{{ pgpool_health_check_database }}"
    query: CREATE EXTENSION {{ item }}
  loop: "{{ pgpool_extensions }}"
  become: true
  become_user: "{{ pgpool_postgresql_service_user }}"
  ignore_errors: true # todo : execute only on the primary node using postgresql_info or else

- name: Apt | Shutdown systemd-based instance upon first installation
  ansible.builtin.service:
    name: pgpool2
    state: stopped
  when: pgpool_install.changed
