---
- name: Configure | Generated hashed passwords for Ansible
  ansible.builtin.set_fact:
    pgpool_password_hashed: "{{ pgpool_password_cleartext | password_hash('sha512') }}"
    pgpool_postgres_password_hashed: "{{ pgpool_postgres_password_cleartext | password_hash('sha512') }}"

- name: Configure | Create pgpool group
  ansible.builtin.group:
    name: "{{ pgpool_group }}"
    state: present

- name: Configure | Ensure the user postgres is added the pgpool group
  ansible.builtin.user:
    name: postgres
    groups: "{{ pgpool_group }}"
    append: true
    password: "{{ pgpool_postgres_password_hashed }}"
    update_password: always

- name: Configure | Create pgpool user
  ansible.builtin.user:
    name: "{{ pgpool_user }}"
    shell: /bin/bash
    home: "{{ pgpool_home_directory }}"
    password: "{{ pgpool_password_hashed }}"
    update_password: always
    group: "{{ pgpool_group }}"

- name: Configure | Update pgpool user's file permissions
  ansible.builtin.file:
    path: "{{ pgpool_home_directory }}"
    owner: "{{ pgpool_user }}"
    group: "{{ pgpool_group }}"
    mode: "0775"
    recurse: true

- name: Configure | Add sudo privileges for pgpool group
  ansible.builtin.template:
    src: sudoers.pgpool.j2
    dest: "/etc/sudoers.d/{{ pgpool_user }}"
    mode: "0644"

- name: Configure | Create socket
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ pgpool_user }}"
    group: "{{ pgpool_group }}"
    mode: "0775"
  loop:
    - "{{ pgpool_socket_dir }}"
    - "{{ pgpool_pcp_socket_dir }}"
    - "{{ pgpool_wd_ipc_socket_dir }}"

- name: Configure | Upload pgpool.conf
  ansible.builtin.template:
    src: pgpool.conf.j2
    dest: "{{ pgpool_home_directory }}/pgpool.conf"
    owner: "{{ pgpool_user }}"
    group: "{{ pgpool_group }}"
    mode: "0775"
  notify: Reload pgpool2

- name: Configure | Upload pool_hba.conf
  ansible.builtin.template:
    src: pool_hba.conf.j2
    dest: "{{ pgpool_home_directory }}/pool_hba.conf"
    owner: "{{ pgpool_user }}"
    group: "{{ pgpool_group }}"
    mode: "0775"
  when:
    - pgpool_enable_pool_hba | bool
    - pgpool_pool_hba_entries | length > 0

- name: Configure | Upload pcp.conf
  ansible.builtin.template:
    src: pcp.conf.j2
    dest: "{{ pgpool_home_directory }}/pcp.conf"
    owner: "{{ pgpool_user }}"
    group: "{{ pgpool_group }}"
    mode: "0775"

- name: Configure | Upload .pcppass file (pgpool)
  ansible.builtin.template:
    src: pcppass.j2
    dest: "{{ pgpool_home_directory }}/.pcppass"
    owner: "{{ pgpool_user }}"
    group: "{{ pgpool_group }}"
    mode: "0600"

- name: Configure | Upload .pcppass file (postgres)
  ansible.builtin.template:
    src: pcppass.j2
    dest: "{{ pgpool_postgresql_home_directory }}/.pcppass"
    owner: "{{ pgpool_postgresql_service_user }}"
    group: "{{ pgpool_postgresql_service_group }}"
    mode: "0600"

- name: Configure | Upload .pgpass file for postgres user
  ansible.builtin.template:
    src: pgpass.j2
    dest: "{{ pgpool_postgresql_home_directory }}/.pgpass"
    owner: "{{ pgpool_postgresql_service_user }}"
    group: "{{ pgpool_postgresql_service_group }}"
    mode: "0600"
    trim_blocks: false
  when: pgpool_pgpass_entries | length > 0

- name: Configure | Upload .pgpoolkey file for pgpool user ( for generation of pool_passwd)
  ansible.builtin.template:
    src: pgpoolkey.j2
    dest: "{{ pgpool_home_directory }}/.pgpoolkey"
    owner: "{{ pgpool_user }}"
    group: "{{ pgpool_group }}"
    mode: "0600"
    trim_blocks: false
  when: pgpool_passwd_use_sha256 | bool

- name: Configure | Upload .pgpoolkey file for postgres user ( to have connections work)
  ansible.builtin.template:
    src: pgpoolkey.j2
    dest: "{{ pgpool_postgresql_home_directory }}/.pgpoolkey"
    owner: "{{ pgpool_postgresql_service_user }}"
    group: "{{ pgpool_postgresql_service_group }}"
    mode: "0600"
    trim_blocks: false
  when: pgpool_passwd_use_sha256 | bool

- name: Configure | Upload pgpool_node_id file for pgpool2 watchdog
  ansible.builtin.template:
    src: pgpool_node_id.j2
    dest: "{{ pgpool_home_directory }}/pgpool_node_id"
    owner: "{{ pgpool_postgresql_service_user }}"
    group: "{{ pgpool_postgresql_service_group }}"
    mode: "0600"

- name: Configure | Copy .bashrc
  ansible.builtin.copy:
    src: /etc/skel/.bashrc
    dest: "{{ pgpool_home_directory }}/.bashrc"
    owner: "{{ pgpool_user }}"
    group: "{{ pgpool_group }}"
    mode: "0600"
    remote_src: true

- name: Configure | Upload .bash_aliases file
  ansible.builtin.template:
    src: bash_aliases.j2
    dest: "{{ pgpool_home_directory }}/.bash_aliases"
    owner: "{{ pgpool_user }}"
    group: "{{ pgpool_group }}"
    mode: "0600"

- name: Configure | Generate pool_passwd file using md5 auth method
  ansible.builtin.shell:
    cmd: |
      pg_md5 --md5auth --username={{ item.username }} {{ item.password }}
  loop: "{{ pgpool_passwd_users_md5 }}"
  when: pgpool_passwd_use_md5 | bool
  become_user: "{{ pgpool_user }}"

- name: Configure | Generate pool_passwd file using pg_enc auth method
  ansible.builtin.shell:
    cmd: |
      pg_enc -m -f "{{ pgpool_home_directory }}/pgpool.conf" --username={{ item.username }} {{ item.password }}
  loop: "{{ pgpool_passwd_users_sha256 }}"
  when: pgpool_passwd_use_sha256 | bool
  become_user: "{{ pgpool_user }}"

- name: PostgreSQL and Pgpool2 | set owner and umask for certifcates to postgres
  ansible.builtin.shell:
    cmd: |
      chown postgres /etc/pgpool2/server.key /etc/pgpool2/server.cert
      chmod 0600 /etc/pgpool2/server.key /etc/pgpool2/server.cert
    executable: /bin/bash
  become: true
  become_user: "root"
  ignore_errors: true

- name: Mask systemd timers that auto-upgrade - apt-daily
  ansible.builtin.systemd:
    name: apt-daily.service
    masked: true
    enabled: false

- name: Mask systemd timers that auto-upgrade - apt-daily-upgrade
  ansible.builtin.systemd:
    name: apt-daily-upgrade.service
    masked: true
    enabled: false

- name: Force systemd to reread configs
  ansible.builtin.systemd:
    daemon_reload: true