---
- name: Syslog | Create initial pgpool logfile
  file:
    path: "{{ pgpool_logdir }}/pgpool.log"
    mode: 0775
    state: touch
    owner: "{{ pgpool_user }}"
    group: "{{ pgpool_group }}"

- name: Syslog | Create logrotate configuration
  template:
    src: pgpool.logrotate.j2
    dest: /etc/logrotate.d/pgpool

- name: Syslog | Update syslog facility
  lineinfile:
    path: /etc/systemd/system/multi-user.target.wants/pgpool2.service
    regex: ^SyslogFacility=
    line: SyslogFacility={{ pgpool_syslog_facility | lower }}
  notify: reload pgpool2

- name: Syslog | Update rsyslog configuration
  template:
    src: rsyslog.pgpool.conf.j2
    dest: /etc/rsyslog.d/pgpool.conf
  notify: restart rsyslog
