---
- name: Restart rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted
    daemon_reload: yes

- name: Reload pgpool2
  ansible.builtin.systemd:
    name: pgpool2
    state: reloaded
  when: pgpool2_running
